"""add payment mc and age fields to visits

Revision ID: 184269d4ecb6
Revises: 1f82fc98381b
Create Date: 2026-01-31 02:00:45.773822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '184269d4ecb6'
down_revision: Union[str, Sequence[str], None] = '1f82fc98381b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('age_at_visit', sa.String(), nullable=True))
    op.add_column('visits', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('visits', sa.Column('receipt_number', sa.String(), nullable=True))
    op.add_column('visits', sa.Column('mc_days', sa.Integer(), nullable=True))
    op.add_column('visits', sa.Column('mc_start_date', sa.Date(), nullable=True))
    op.add_column('visits', sa.Column('mc_end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visits', 'mc_end_date')
    op.drop_column('visits', 'mc_start_date')
    op.drop_column('visits', 'mc_days')
    op.drop_column('visits', 'receipt_number')
    op.drop_column('visits', 'payment_method')
    op.drop_column('visits', 'age_at_visit')
    # ### end Alembic commands ###
