"""add notes to dispensation_items

Revision ID: 1f82fc98381b
Revises: c34179311737
Create Date: 2026-01-30 16:54:22.962294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f82fc98381b'
down_revision: Union[str, Sequence[str], None] = 'c34179311737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispensation_items', sa.Column('notes', sa.String(), nullable=True))
    op.drop_constraint(op.f('uq_patients_display_id'), 'patients', type_='unique')
    op.create_index(op.f('ix_patients_display_id'), 'patients', ['display_id'], unique=True)
    op.create_index(op.f('ix_visits_patient_id'), 'visits', ['patient_id'], unique=False)
    op.drop_constraint(op.f('visits_patient_id_fkey'), 'visits', type_='foreignkey')
    op.create_foreign_key(None, 'visits', 'patients', ['patient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visits', type_='foreignkey')
    op.create_foreign_key(op.f('visits_patient_id_fkey'), 'visits', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_visits_patient_id'), table_name='visits')
    op.drop_index(op.f('ix_patients_display_id'), table_name='patients')
    op.create_unique_constraint(op.f('uq_patients_display_id'), 'patients', ['display_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('dispensation_items', 'notes')
    # ### end Alembic commands ###
