"""Add date_registered to patients

Revision ID: 5b93ed346cd3
Revises: 7d4a03267b62
Create Date: 2026-01-29 16:36:04.991780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b93ed346cd3'
down_revision: Union[str, Sequence[str], None] = '7d4a03267b62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('date_registered', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'date_registered')
    # ### end Alembic commands ###
