"""initial_full_schema

Revision ID: 7563ee11136c
Revises: 
Create Date: 2026-02-08 21:57:51.350753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7563ee11136c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_id', sa.String(), nullable=False),
    sa.Column('date_registered', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('phone_number_primary', sa.String(), nullable=False),
    sa.Column('phone_number_secondary', sa.String(), nullable=True),
    sa.Column('father_name', sa.String(), nullable=True),
    sa.Column('father_occupation', sa.String(), nullable=True),
    sa.Column('mother_name', sa.String(), nullable=True),
    sa.Column('mother_occupation', sa.String(), nullable=True),
    sa.Column('para', sa.String(), nullable=True),
    sa.Column('languages_parents', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('languages_children', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('hospital', sa.String(), nullable=True),
    sa.Column('delivery', sa.String(), nullable=True),
    sa.Column('birth_weight_kg', sa.Float(), nullable=True),
    sa.Column('birth_length_cm', sa.Float(), nullable=True),
    sa.Column('birth_ofc_cm', sa.Integer(), nullable=True),
    sa.Column('g6pd', sa.String(), nullable=True),
    sa.Column('tsh_mlul', sa.Integer(), nullable=True),
    sa.Column('feeding', sa.String(), nullable=True),
    sa.Column('allergies', sa.String(), nullable=True),
    sa.Column('vaccination_summary', sa.String(), nullable=True),
    sa.Column('other_notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_date_of_birth'), 'patients', ['date_of_birth'], unique=False)
    op.create_index(op.f('ix_patients_display_id'), 'patients', ['display_id'], unique=True)
    op.create_index(op.f('ix_patients_name'), 'patients', ['name'], unique=False)
    op.create_table('system_configs',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_system_configs_key'), 'system_configs', ['key'], unique=False)
    op.create_table('patient_siblings',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('sibling_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['sibling_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('patient_id', 'sibling_id')
    )
    op.create_table('visits',
    sa.Column('visit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('age_at_visit', sa.String(), nullable=True),
    sa.Column('doctor_notes', sa.String(), nullable=True),
    sa.Column('total_charge', sa.Float(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('receipt_number', sa.String(), nullable=True),
    sa.Column('mc_days', sa.Integer(), nullable=True),
    sa.Column('mc_start_date', sa.Date(), nullable=True),
    sa.Column('mc_end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('visit_id')
    )
    op.create_index(op.f('ix_visits_date'), 'visits', ['date'], unique=False)
    op.create_index(op.f('ix_visits_patient_id'), 'visits', ['patient_id'], unique=False)
    op.create_table('dispensation_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('medicine_name', sa.String(), nullable=False),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('quantity', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_dispensed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.visit_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispensation_items_visit_id'), 'dispensation_items', ['visit_id'], unique=False)
    op.create_table('visit_attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.visit_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_attachments_visit_id'), 'visit_attachments', ['visit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visit_attachments_visit_id'), table_name='visit_attachments')
    op.drop_table('visit_attachments')
    op.drop_index(op.f('ix_dispensation_items_visit_id'), table_name='dispensation_items')
    op.drop_table('dispensation_items')
    op.drop_index(op.f('ix_visits_patient_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_date'), table_name='visits')
    op.drop_table('visits')
    op.drop_table('patient_siblings')
    op.drop_index(op.f('ix_system_configs_key'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_patients_name'), table_name='patients')
    op.drop_index(op.f('ix_patients_display_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_date_of_birth'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
