"""added follow-up to Visit

Revision ID: a84ff7b0f1b5
Revises: 7563ee11136c
Create Date: 2026-02-10 16:51:07.563614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a84ff7b0f1b5'
down_revision: Union[str, Sequence[str], None] = '7563ee11136c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('follow_up', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visits', 'follow_up')
    # ### end Alembic commands ###
