"""Added indexes

Revision ID: e543a24fcca9
Revises: 5b93ed346cd3
Create Date: 2026-01-29 17:36:30.639294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e543a24fcca9'
down_revision: Union[str, Sequence[str], None] = '5b93ed346cd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_patients_date_of_birth'), 'patients', ['date_of_birth'], unique=False)
    op.create_index(op.f('ix_patients_name'), 'patients', ['name'], unique=False)
    op.create_index(op.f('ix_visit_attachments_visit_id'), 'visit_attachments', ['visit_id'], unique=False)
    op.create_index(op.f('ix_visits_date'), 'visits', ['date'], unique=False)
    op.create_index(op.f('ix_visits_patient_id'), 'visits', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visits_patient_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_date'), table_name='visits')
    op.drop_index(op.f('ix_visit_attachments_visit_id'), table_name='visit_attachments')
    op.drop_index(op.f('ix_patients_name'), table_name='patients')
    op.drop_index(op.f('ix_patients_date_of_birth'), table_name='patients')
    # ### end Alembic commands ###
